name: Infra Multi-Env Infra Pipeline1234

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment'
        required: true
        type: choice
        options:        
          - sit
          - uat
          - production
      working_directory:
        description: 'Terraform directory path'
        required: true
        default: '.'
        type: string

jobs:  
  Deploy:
    
    uses: Aayu1983/centeral-repo/.github/workflows/terraform-template-multi.yml@main
    with:
      environment: ${{ github.event.inputs.target_env }}
      working_directory: ${{ github.event.inputs.working_directory }}
      tf_state_key: "${{ github.event.inputs.target_env }}.tfstate"
    secrets: 
      client_id: ${{ secrets.CLIENT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      tenant_id: ${{ secrets.TENANT_ID }}
      resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
      storage_account_name: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      container_name: ${{ secrets.CONTAINER_NAME }}
